name: Build Base Image (Heavy Dependencies)

on:
  push:
    branches: [main]
    paths:
      - ".devcontainer/Dockerfile.base"
      - ".github/workflows/build-base-image.yml"
  workflow_dispatch:

# This builds the HEAVY base image with Node, Rust, WASM targets
# Only runs when you update dependencies, not every commit

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/fastedge-app/base

jobs:
  build-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: .devcontainer
          file: .devcontainer/Dockerfile.base
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline
          platforms: linux/amd64
